#!/bin/sh
#Script Directory
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#Define the version filename
FILENAME=$(realpath $SCRIPT_DIR/../version.txt)
exec 2>&1
#Check if the file exists
if [ -f "$FILENAME" ]; then
    #If the file exists, print its contents to stdout
    cat "$FILENAME"
fi
python $(realpath $SCRIPT_DIR/../dbus-opendtu.py)
